import Foundation

struct Manifest: Decodable {
    let teams: [Team]
}

struct Team: Decodable {
    let stableID: String
    let name: String
    let abbreviation: String
    let primaryColorHex: String
    let secondaryColorHex: String
    let assetName: String
    let generationStatus: String
    let humanApproved: Bool
}

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let manifestURL = root.appendingPathComponent("Tools/TeamLogos/manifest.json")
let outputURL = root.appendingPathComponent(
    "Sources/ProFootballCoachUI/TeamLogoCatalog.generated.swift"
)
let manifest = try JSONDecoder().decode(
    Manifest.self,
    from: Data(contentsOf: manifestURL)
)
guard manifest.teams.count == 166,
      manifest.teams.allSatisfy({ $0.generationStatus == "approved" && $0.humanApproved })
else { fatalError("catalogue requires 166 owner-approved logo records") }

let teams = manifest.teams.sorted { $0.stableID < $1.stableID }
let entries = teams
    .map { "        \"\($0.stableID)\": \"\($0.assetName)\"," }
    .joined(separator: "\n")

func swiftLiteral(_ value: String) -> String {
    value.replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

let proofEntries = teams
    .map { team in
        "        CoachWorldTeamReference(stableID: \"\(team.stableID)\", "
            + "name: \"\(swiftLiteral(team.name))\", "
            + "abbreviation: \"\(team.abbreviation)\", "
            + "mark: mark(forStableID: \"\(team.stableID)\"), "
            + "primaryColorHex: \"\(team.primaryColorHex)\", "
            + "secondaryColorHex: \"\(team.secondaryColorHex)\"),"
    }
    .joined(separator: "\n")

let source = """
// Generated by Tools/TeamLogos/generate_catalog.swift. Do not hand-edit.
public enum CoachWorldTeamLogoCatalog {
    public static func mark(forStableID stableID: String) -> CoachWorldAssetReference? {
        assetNames[stableID].map {
            CoachWorldAssetReference(stableID: stableID, assetName: $0)
        }
    }

    private static let assetNames: [String: String] = [
\(entries)
    ]

    #if DEBUG
    static let proofTeams: [CoachWorldTeamReference] = [
\(proofEntries)
    ]
    #endif
}
"""

try source.write(to: outputURL, atomically: true, encoding: .utf8)
